package com.mum.carpool.domain_test;
// Generated Sep 23, 2016 3:44:29 PM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * C3p0TestTable generated by hbm2java
 */
@Entity
@Table(name = "C3P0_TEST_TABLE", catalog = "carpoolingdb")
public class C3p0TestTable implements java.io.Serializable {

	private Character a;

	public C3p0TestTable() {
	}

	public C3p0TestTable(Character a) {
		this.a = a;
	}

	@Id

	@Column(name = "a", length = 1)
	public Character getA() {
		return this.a;
	}

	public void setA(Character a) {
		this.a = a;
	}

}
