package com.mum.carpool.domain;
// Generated Aug 31, 2016 12:45:48 PM by Hibernate Tools 5.1.0.Beta1

/**
 * C3p0TestTable generated by hbm2java
 */
public class C3p0TestTable implements java.io.Serializable {

	private Character a;

	public C3p0TestTable() {
	}

	public C3p0TestTable(Character a) {
		this.a = a;
	}

	public Character getA() {
		return this.a;
	}

	public void setA(Character a) {
		this.a = a;
	}

}
