package com.mum.carpool.domain;
// Generated Aug 31, 2016 12:45:48 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Likes generated by hbm2java
 */
public class Likes implements java.io.Serializable {

	private Integer likeid;
	private int userid;
	private int postid;
	private Date datecreated;
	private Date dateupdated;

	public Likes() {
	}

	public Likes(int userid, int postid, Date datecreated, Date dateupdated) {
		this.userid = userid;
		this.postid = postid;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
	}

	public Integer getLikeid() {
		return this.likeid;
	}

	public void setLikeid(Integer likeid) {
		this.likeid = likeid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getPostid() {
		return this.postid;
	}

	public void setPostid(int postid) {
		this.postid = postid;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}

}
