package com.mum.carpool.domain;
// Generated Aug 30, 2016 4:24:04 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import java.util.List;

/**
 * Posts generated by hbm2java
 */
public class Posts implements java.io.Serializable {

	private Integer postid;
	private Integer userid;
	private User user;
	private String post;
	private int posttype;
	private Date datecreated;
	private Date dateupdated;
	private List<Comments> comments;
	private int likes;
	private boolean isthisuserliked;
	
	public Posts() {
	}

	public Posts(int userid, String post, int posttype, Date datecreated, Date dateupdated) {
		this.user = user;
		//this.userid = userid;
		this.post = post;
		this.posttype = posttype;
		this.datecreated = datecreated;
		this.dateupdated = dateupdated;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}
	
	public Integer getPostid() {
		return this.postid;
	}

	public void setPostid(Integer postid) {
		this.postid = postid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	public int getPosttype() {
		return this.posttype;
	}

	public void setPosttype(int posttype) {
		this.posttype = posttype;
	}

	public Date getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(Date datecreated) {
		this.datecreated = datecreated;
	}

	public Date getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(Date dateupdated) {
		this.dateupdated = dateupdated;
	}
	

	public List<Comments> getComments() {
		return comments;
	}

	public void setComments(List<Comments> comments) {
		this.comments = comments;
	}
	
	public int getLikes() {
		return likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

	public boolean getIsthisuserliked() {
		return isthisuserliked;
	}

	public void setIsthisuserliked(boolean isthisuserliked) {
		this.isthisuserliked = isthisuserliked;
	}


}